### ISSUE TITLE
API key for OpenWeatherMap

### ISSUE THREAD

**Issue by jagodki** [klakar/QGIS_resources#6]
Hej Klas,

You provide a python script to include some basemap services into QGIS: collections/Geosupportsystem/python/qgis_basemaps.py

The script contains services from OpenWeatherMap, inclusive a mandatory and valid API key. Do you know the owner of this key or what are the restrictions for the usage of the OpenWeatherMap services with this key?

Best regards,
Christoph

**Comment by klakar** [comment]
The URL:s were collected from the QuickMapServices plugin for QGIS when I wrote the script.
They seem to have removed the source since then, so the APPID (API key) is probably not valid for wide usage...
Thanks for bringing it up and I've modified the source so it does not include the keys any more.
Users will need to add their own keys.

**Comment by klakar** [comment]
The original submitted source is still available though, at: https://qms.nextgis.com/geoservices/1301/
And the rest is also at the same base url. The "uploader" is _Saijin_Naib_ but it is not clear if he also is the owner of the keys.

**Comment by jagodki** [comment]
Thank you for your clarification 👍
